### PR TITLE
Additional APIs and initial Jest setup

### PR DESCRIPTION
**Pull request by matt-leyrat**
Lots of work on this one: 

- **Implementation:**
  - GET route for single item (along with related DB functionality)
  - Unit test for getNRandomElements function
  - Test file for seed script (with 1 simple test)
  - Style-guide violation fixes

- **New dependencies:**
  - eslint
  - Jest
  - Enzyme

- **Current issues:**
  - Wrestling with setting up my Async database functionality to play nicely with Jest. Here's the error message I'm dealing with: 

```Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.```

### CODE REVIEW

**Comment by gchzhen** [comment]
Love your workflow, how often your commit and how modular and easy to read your code is. Regarding your wrestling with testing, I feel you, try to add --detectOpenHandles in your script in package.JSON file:

"scripts": {
    "test": "jest --detectOpenHandles"
  }

I haven't figured the whole thing yet, but hopefully we'll do it today!

**Comment by matt-leyrat** [comment]
Thanks @gchzhen ! I'm going to try that and let you know what happens.

**Comment by matt-leyrat** [comment]
I'm actually not getting that error message anymore now that I added that to my script.. But Jest isn't shutting down after finishing all of the tests.

**Comment by matt-leyrat** [comment]
I was able to get it to exit after completing all of the tests by using --forceExit but I have a feeling this isn't going to be sustainable in the near future.

**Pull request merged**
